name: Build
on:
  push:
  workflow_dispatch:

jobs:
  compile:
    name: Compile for all changed languages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile services by language
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: build.sh
        shell: bash
